### ISSUE TITLE
you wrote your own password into a public repo. Congrats.

### ISSUE THREAD

**Issue by cpawley** [AviatorRoyal/SECTOR-MANAGER#2]
https://github.com/AviatorRoyal/SECTOR-MANAGER/blob/7ab1327ca59a8d0d1fd8a883e6bffe6f1712274b/SECTOR%20MANAGER%20DEVS/NIGHTLY/6.11.23/SECTOR%20MANAGER/input.sectors/VABF-Install_20210708113747-210601-0001/VABF-Ground.prf#L74

**Comment by AviatorRoyal** [comment]
Hey Chris,
Thanks for checking in... Don't worry I have changed my password.
Regards
